version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:4200"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379 
volumes:
  data: